networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mkwizera/data/wordpress
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mkwizera/data/mariadb

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

services:
  mariadb:
    image: mariadb:v1
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    image: wordpress:v1
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_HOST: mariadb
    depends_on:
      - mariadb
    secrets:
      - db_password
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:v1
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
